### ISSUE TITLE
Add support for subscriptions-transport-ws protocol

### ISSUE THREAD

**Issue by BratSinot** [obmarg/graphql-ws-client#16]
For now lib support only `graphql-transport-ws` protocol.
May be add `subscriptions-transport-ws` as well (they very similar):
https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md

**Comment by obmarg** [comment]
I can’t remember where I read it, but my understanding was that graphql-transport-ws superseded graphql-ws - which is part of why I only support the one. 

Not against supporting the other if anyone needs it though

**Comment by BratSinot** [comment]
I created this issue only for non-forget. `async-graphql` lib which I use, support both of them, so, yeah, nothing important actually.

**Comment by obmarg** [comment]
👍

**Comment by Sytten** [comment]
`graphql-transport-ws ` is actually the old crappy protocol of apollo and `graphql-ws` is the newer one on which the spec is going to be based eventually.

**Comment by HuakunShen** [comment]
Any update on this? Is `graphql-ws` supported?

**Comment by obmarg** [comment]
@HuakunShen 

[`graphql-ws`](https://github.com/enisdenjo/graphql-ws/tree/master) _is_ supported.  
[`subscriptions-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) is not, and probably never will be.

**Comment by HuakunShen** [comment]
@obmarg Thanks

**Comment by Kuzirashi** [comment]
It seems that changing stuff in: `src/protocol.rs` helps a bit:
```
#[derive(serde::Serialize)]
#[serde(tag = "type")]
pub enum Message<'a, Operation> {
    #[serde(rename = "start")]
    Subscribe { id: String, payload: &'a Operation },
    #[serde(rename = "stop")]
    #[allow(dead_code)]
    Complete { id: String },
    #[serde(rename = "pong")]
    Pong,
}
```

**Comment by obmarg** [comment]
I'm going to close this issue - `subscriptions-transport-ws` is deprecated and I've no plans to support it.

If someone wants support for that protocol I'd suggest they make a fork.
