### ISSUE TITLE
Error: `WebsocketMessage` is not implemented for `Message`

### ISSUE THREAD

**Issue by half0wl** [obmarg/graphql-ws-client#46]
I'm encountering this error:
```
error[E0277]: the trait bound `Message: WebsocketMessage` is not satisfied
   --> src/subscription.rs:69:10
    |
69  |         .build(stream, sink, as...
    |          ^^^^^ the trait `WebsocketMessage` is not implemented for `Message`
    |
```
when using the example in https://github.com/obmarg/graphql-ws-client/blob/main/examples/examples/subscriptions.rs.

I'm using the examples as-is, but perhaps I'm missing something obvious?

**Comment by obmarg** [comment]
Hi @half0wl - thanks for the report.  Looks like the version of `async_tungstenite` in the examples didn't match the one `graphql-ws-client` expected.  Have filed #47 to fix and updated the tests so this can't happen again.
