### ISSUE TITLE
Library not working with cynic `3.2.2`

### ISSUE THREAD

**Issue by boyswan** [obmarg/graphql-ws-client#49]
Currently this library does not work with the latest version of cynic.

I changed https://github.com/obmarg/graphql-ws-client/blob/main/src/graphql.rs#L76 to also take `Variables` which allows the code based on the example to compile, but I'm unsure whether other changes are required.

**Comment by obmarg** [comment]
Oh, silly me - I forgot this library needs updated after I changed a few things in cynic.

I'll try and get round to that soon - although I'd be happy to accept a PR if you feel like making one

**Comment by boyswan** [comment]
If I can get it working I'll make a PR! I've got it compiling, but it doesn't seem to be sending/receiving messages. Will let you know if I get anywhere.

**Comment by obmarg** [comment]
Hey @boyswan - so I've done the upgrade in #50, and added a test just to make sure everything is working.

I didn't really need any changes beyond the one you mentioned though...

**Comment by obmarg** [comment]
Haven't heard back from you @boyswan - so I'm going to close this.  Feel free to re-open if you're still having problems.
