### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by obmarg** [obmarg/graphql-ws-client#5]
The client would benefit from adding `log`s so we have a place to print out errors or warnigns when things go wrong.  This is to track adding them.

**Comment by BratSinot** [comment]
What about https://docs.rs/tracing lib?

**Comment by obmarg** [comment]
I'm not sure about adding tracing here.  It's a great library and I use it in most of my services at work, but I don't know whether I want to force it on every user of `graphql-ws-client`.

I'd be more comfortable just using the normal `log` crate for now, unless people start demanding tracing support (which I'd probably want to either put behind a feature flag, or have as some sort of extension crate).
