### ISSUE TITLE
The library has no tests

### ISSUE THREAD

**Issue by obmarg** [obmarg/graphql-ws-client#9]
Haven't got round to writing any tests yet.  This needs fixed before a release.

Also need CI etc (probably github actions?)

**Comment by obmarg** [comment]
Want to make sure I test shutdown behaviour in particular...

**Comment by Sytten** [comment]
We should revisit that a some point.

**Comment by obmarg** [comment]
[This is no longer true](https://github.com/obmarg/graphql-ws-client/blob/main/tests/cynic-tests.rs) so closing this.
